/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as UploadReportRouteImport } from './routes/upload-report'
import { Route as TriageResultsRouteImport } from './routes/triage-results'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as IndexRouteImport } from './routes/index'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadReportRoute = UploadReportRouteImport.update({
  id: '/upload-report',
  path: '/upload-report',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageResultsRoute = TriageResultsRouteImport.update({
  id: '/triage-results',
  path: '/triage-results',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/symptoms': typeof SymptomsRoute
  '/triage-results': typeof TriageResultsRoute
  '/upload-report': typeof UploadReportRoute
  '/verify-otp': typeof VerifyOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/symptoms': typeof SymptomsRoute
  '/triage-results': typeof TriageResultsRoute
  '/upload-report': typeof UploadReportRoute
  '/verify-otp': typeof VerifyOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/symptoms': typeof SymptomsRoute
  '/triage-results': typeof TriageResultsRoute
  '/upload-report': typeof UploadReportRoute
  '/verify-otp': typeof VerifyOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camps'
    | '/chat'
    | '/home'
    | '/hospitals'
    | '/language'
    | '/login'
    | '/pharmacies'
    | '/records'
    | '/register'
    | '/schemes'
    | '/symptoms'
    | '/triage-results'
    | '/upload-report'
    | '/verify-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camps'
    | '/chat'
    | '/home'
    | '/hospitals'
    | '/language'
    | '/login'
    | '/pharmacies'
    | '/records'
    | '/register'
    | '/schemes'
    | '/symptoms'
    | '/triage-results'
    | '/upload-report'
    | '/verify-otp'
  id:
    | '__root__'
    | '/'
    | '/camps'
    | '/chat'
    | '/home'
    | '/hospitals'
    | '/language'
    | '/login'
    | '/pharmacies'
    | '/records'
    | '/register'
    | '/schemes'
    | '/symptoms'
    | '/triage-results'
    | '/upload-report'
    | '/verify-otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampsRoute: typeof CampsRoute
  ChatRoute: typeof ChatRoute
  HomeRoute: typeof HomeRoute
  HospitalsRoute: typeof HospitalsRoute
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  PharmaciesRoute: typeof PharmaciesRoute
  RecordsRoute: typeof RecordsRoute
  RegisterRoute: typeof RegisterRoute
  SchemesRoute: typeof SchemesRoute
  SymptomsRoute: typeof SymptomsRoute
  TriageResultsRoute: typeof TriageResultsRoute
  UploadReportRoute: typeof UploadReportRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-report': {
      id: '/upload-report'
      path: '/upload-report'
      fullPath: '/upload-report'
      preLoaderRoute: typeof UploadReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage-results': {
      id: '/triage-results'
      path: '/triage-results'
      fullPath: '/triage-results'
      preLoaderRoute: typeof TriageResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampsRoute: CampsRoute,
  ChatRoute: ChatRoute,
  HomeRoute: HomeRoute,
  HospitalsRoute: HospitalsRoute,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  PharmaciesRoute: PharmaciesRoute,
  RecordsRoute: RecordsRoute,
  RegisterRoute: RegisterRoute,
  SchemesRoute: SchemesRoute,
  SymptomsRoute: SymptomsRoute,
  TriageResultsRoute: TriageResultsRoute,
  UploadReportRoute: UploadReportRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
